import type { Account } from "./account";
import { assertAccountUsable } from "./account";
import { DomainError } from "./errors";
import type { Money } from "./money";

export interface FxSnapshot { readonly rateScaled: number; readonly rateScale: number; readonly date: string; readonly source: string; }
export interface Transaction { readonly id:string; readonly operationId:string; readonly kind:"income"|"expense"; readonly amount:Money; readonly baseAmount:Money; readonly accountId:string; readonly categoryId:string; readonly occurredAt:string; readonly localDate:string; readonly note:string; readonly fx:FxSnapshot|null; readonly createdBy:string; readonly updatedBy:string; readonly createdAt:string; readonly updatedAt:string; readonly version:number; readonly deletedAt:string|null; }
export interface CreateTransactionInput { id:string; operationId:string; kind:"income"|"expense"; amount:Money; baseAmount:Money; account:Account; categoryId:string; occurredAt:string; localDate:string; note:string; actorUid:string; fx:FxSnapshot|null; }
export type TransactionChanges = Partial<Pick<Transaction,"categoryId"|"occurredAt"|"localDate"|"note">>;

function text(v:string,n:string){if(!v.trim())throw new DomainError("INVALID_TRANSACTION_FIELD",`${n} is required`);return v.trim();}
function instant(v:string){if(!/^\d{4}-\d{2}-\d{2}T/.test(v)||Number.isNaN(Date.parse(v)))throw new DomainError("INVALID_TRANSACTION_DATE","Transaction instant is invalid");}
function date(v:string){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(v);if(!m)throw new DomainError("INVALID_TRANSACTION_DATE","Transaction local date is invalid");const d=new Date(Date.UTC(+m[1],+m[2]-1,+m[3]));if(d.getUTCFullYear()!=+m[1]||d.getUTCMonth()!=+m[2]-1||d.getUTCDate()!=+m[3])throw new DomainError("INVALID_TRANSACTION_DATE","Transaction local date is invalid");}
function version(t:Transaction,v:number){if(t.version!==v)throw new DomainError("TRANSACTION_VERSION_CONFLICT","Transaction version conflict");}
function validateFx(i:CreateTransactionInput){if(i.amount.currency!==i.account.currency)throw new DomainError("ACCOUNT_CURRENCY_MISMATCH","Transaction currency must match account currency");if(i.amount.amountMinor<=0||i.baseAmount.amountMinor<=0)throw new DomainError("INVALID_TRANSACTION_AMOUNT","Transaction amount must be positive");if(i.amount.currency!==i.baseAmount.currency&&!i.fx)throw new DomainError("FX_REQUIRED","FX snapshot is required");if(i.fx&&(!Number.isSafeInteger(i.fx.rateScaled)||i.fx.rateScaled<=0||!Number.isSafeInteger(i.fx.rateScale)||i.fx.rateScale<=0))throw new DomainError("INVALID_FX","FX snapshot is invalid");}
export function createTransaction(i:CreateTransactionInput,now:string):Transaction{assertAccountUsable(i.account);validateFx(i);instant(i.occurredAt);instant(now);date(i.localDate);return Object.freeze({id:text(i.id,"id"),operationId:text(i.operationId,"operationId"),kind:i.kind,amount:i.amount,baseAmount:i.baseAmount,accountId:i.account.id,categoryId:text(i.categoryId,"categoryId"),occurredAt:i.occurredAt,localDate:i.localDate,note:i.note.trim(),fx:i.fx,createdBy:text(i.actorUid,"actorUid"),updatedBy:i.actorUid.trim(),createdAt:now,updatedAt:now,version:1,deletedAt:null});}
export function updateTransaction(t:Transaction,v:number,c:TransactionChanges,actor:string,now:string):Transaction{version(t,v);instant(now);if(c.occurredAt)instant(c.occurredAt);if(c.localDate)date(c.localDate);return Object.freeze({...t,...c,categoryId:c.categoryId===undefined?t.categoryId:text(c.categoryId,"categoryId"),note:c.note===undefined?t.note:c.note.trim(),updatedBy:text(actor,"actorUid"),updatedAt:now,version:t.version+1});}
export function softDeleteTransaction(t:Transaction,v:number,a:string,n:string){version(t,v);return Object.freeze({...t,deletedAt:n,updatedAt:n,updatedBy:text(a,"actorUid"),version:t.version+1});}
export function restoreTransaction(t:Transaction,v:number,a:string,n:string){version(t,v);return Object.freeze({...t,deletedAt:null,updatedAt:n,updatedBy:text(a,"actorUid"),version:t.version+1});}
